apiVersion: v1
kind: Secret
metadata:
  name: ca-saas-db-secret
  namespace: ca-system
  labels:
    app: ca-saas-db
type: Opaque
data:
  POSTGRES_PASSWORD: Y2Ffc2Fhc19wYXNzd29yZA== # base64 for 'ca_saas_password'
