apiVersion: v1
kind: Secret
metadata:
  name: saas-backend-secrets
  namespace: ca-system
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2NhX3NhYXM6Y2Ffc2Fhc19wYXNzd29yZEBjYS1zYWFzLWRiLmNhLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2NhX3NhYXM=  # postgresql://ca_saas:ca_saas_password@ca-saas-db.ca-system.svc.cluster.local:5432/ca_saas
  stripe-secret-key: c2tfdGVzdF81MVNyR0JEUGNBYWo1SWx6eVhFTnVIN09NOWpXU0lVV1pCRE5JbjR3ZnRLTFFaVlFhZkNKTEdrdTRGR2Z0Q1VhZUc2UVA5N3g1aXV5Q0JrM2ZrUmU2dmhWZjAwTnVsNVAxMHQ=
  stripe-webhook-secret: d2hzZWNfYTVmNWEzNzdjYjRlZDFlMmRmMGU4ZWMyNmYxMzkzZTc4YmFlN2U1MGFmNGRhYTIxZGE3MDI1NDJlMjY2OTZjOA==
  db-password: Y2FwYXNzd29yZDEyMw==
