apiVersion: v1
kind: ServiceAccount
metadata:
  name: saas-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: saas-backend-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets", "pods", "pods/exec", "persistentvolumeclaims", "services"]
  verbs: ["create", "get", "list", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: saas-backend-binding
subjects:
- kind: ServiceAccount
  name: saas-backend
  namespace: ca-system 
roleRef:
  kind: ClusterRole
  name: saas-backend-role
  apiGroup: rbac.authorization.k8s.io
