apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenantName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.tenantName }}
  template:
    metadata:
      labels:
        app: {{ .Values.tenantName }}
    spec:
      containers:
        - name: ca
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db
          env:
            - name: CA_TIMEZONE
              value: {{ .Values.app.timezone }}
            - name: CA_ADMIN_EMAIL
              value: {{ .Values.app.adminEmail }}
            - name: CA_INSTANCE_ID
              value: {{ .Values.app.instanceId }}
            - name: CA_TENANT_NAME
              value: {{ .Values.app.tenantDisplayName }}
          volumeMounts:
            - name: media
              mountPath: /var/www/html/ca/media
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Values.tenantName }}-media
