apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tenantName }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.tenantName }}-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.tenantName }}
                port:
                  number: 80
