apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
type: Opaque
stringData:
  DB_NAME: {{ .Values.database.name }}
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_HOST: {{ .Values.database.host | default "mysql.ca-system.svc.cluster.local" }}
  DB_PORT: "3306"
